// <auto-generated />
using System;
using AmplaSettingsEditor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmplaSettingsEditor.Migrations
{
    [DbContext(typeof(AmplaSettingsEditorContext))]
    partial class AmplaSettingsEditorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmplaSettingsEditor.Models.AmplaField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRussian")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RpId");

                    b.Property<string>("RpNameFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RpType");

                    b.Property<string>("SapId")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AmplaField");
                });
#pragma warning restore 612, 618
        }
    }
}
